### PR TITLE
added my code

### PR DESCRIPTION
**Pull request by pallavi2031**
please see my code and merge it.

### CODE REVIEW

**Comment by pallavi2031** [comment]
ma'am please can you tell is this repo was under  hacktoberfest2022 or not ?

**Comment by mo-renike** [comment]
Yes it is

**Comment by pallavi2031** [comment]
thank you so much ma'am it was my first contribution to open source and I did learn a lots in this process .If you don't create this issue then I can't learn all this.

**Comment by mo-renike** [comment]
Awesome! You're welcome

**Comment by pallavi2031** [comment]
ma'am this pr show not participating   in hactoberfest2022 on my profile  .

**Comment by mo-renike** [comment]
oh? what was the issue # the PR fixed?

**Comment by pallavi2031** [comment]
thank you ma'am now showing .

**Pull request merged**
